### ISSUE TITLE
Convert to use App::Mi6

### ISSUE THREAD

**Issue by tbrowder** [jonathanstowe/XML-Class#8]
I will be happy to provide a PR to (1) convert this module to use **mi6** and (2) use **mi6** to extract pod and convert it to Markdown as, say, **./DOCUMENTATION.md**.

My motivation is that I want to use the module in one of my current modules and I like to see the full pod documentation online. **App::Mi6** makes that easy to do: write in pod, see Markdown online on Github!

Then your work flow for changes would be:

+ code changes...
+ mi6 build
+ mi6 test
+ git commit
+ git push
+ repeat until ready 
+ mi6 release ...

Voila!

The PR would:

+ add a **./docs/DOCUMENTATION.pod** file (which would be the pod code removed from your current lib/Class/XML,pm file)
+ convert your **Changes** file to the **mi6** format
+ add a **dist.ini** file
+ convert your current **README.md** file to use the github workflows test results

**Comment by jonathanstowe** [comment]
Hi,
I'm not particularly keen to add a new tool to my workflow for just one module, I have my own set of tools for managing the packaging and upload and don't particularly want something else managing the META6.json or Changes.

It does however have [Documentation.md](https://github.com/jonathanstowe/XML-Class/blob/master/Documentation.md) which is up to date with the POD, which I tend to do with those modules which have non-trivial documentation.

**Comment by tbrowder** [comment]
I apologize, I did see that earlier but forgot about it. My old brain is slowing waaay down. 

Do you plan a new release soon?

I get it, thanks for all your many contributions!

**Comment by tbrowder** [comment]
> I apologize, I did see that earlier but forgot about it. My old brain is slowing waaay down.
> 
> Do you plan a new release soon?

**Comment by tbrowder** [comment]
Closing this issue.

**Comment by tbrowder** [comment]
Closing as N/A.

**Comment by jonathanstowe** [comment]
FWIW, the next major change I'm planning on making to this is to flip it to use `LibXML` rather than `XML`  , mostly for speed and memory reasons, however this may take a while so not making any guarantee as to when that might be.

**Comment by tbrowder** [comment]
Thank you for the update.
